### ISSUE TITLE
Port not used at wrong port

### ISSUE THREAD

**Issue by Simanias** [Piker-Alpha/AppleIntelFramebufferAzul.sh#2]
In the screenshot below you can see the framebuffer says "(port 7, DisplayPort connector / port unused)", but if I try to change a port, it says "[ 4 ] port unused (VGA connector)"
![screen shot 2014-09-11 at 11 23 35](https://cloud.githubusercontent.com/assets/4976061/4231790/6970ee64-3995-11e4-8150-5080a8f4e760.png)
Which port is unused, I guess the VGA connector.
Simania

**Comment by Piker-Alpha** [comment]
There are two port on that line; port 7 (DisplayPort) and the "unused" port (VGA) thus you can only change port 1-3, but a next update will give you control over all ports.

**Comment by Piker-Alpha** [comment]
You can change all ports in v3.0 Beta, and the text has also improved. Please give the latest update a try.
