### ISSUE TITLE
v3.0B Issue after choosing not to reboot

### ISSUE THREAD

**Issue by Simanias** [Piker-Alpha/AppleIntelFramebufferAzul.sh#3]
After patching the Framebuffer and deciding to not reboot the system immediately the following error occurs:
![screen shot 2014-09-17 at 11 34 17](https://cloud.githubusercontent.com/assets/4976061/4301318/da4dc4ba-3e4d-11e4-861a-0d3e7ad4425f.png)

Once again thanks very much Pike for all the effort you put into this!
Simania

**Comment by Piker-Alpha** [comment]
I fail to reproduce this issue, but I will have another look tonight (did find something else that I need to fix).

p.s. What version of OS X are you using?

**Comment by Simanias** [comment]
I'm on 10.9.4

**Comment by Piker-Alpha** [comment]
Ok. Thanks. I will test it with OS X 10.9.4 and see if I can reproduce this issue. Maybe 10.9.4 is somehow different.

Edit: No problem here with 10.9.4 Please try again with the latest script, and delete data files (Azul-0x*.dat) to make sure that you don't run into incompatibility issue.

**Comment by Simanias** [comment]
No idea what caused it, it works now. Thanks
