### ISSUE TITLE
Displayport still seen as unused after connector type editing

### ISSUE THREAD

**Issue by giacomoleopardo** [Piker-Alpha/AppleIntelFramebufferAzul.sh#4]
Hi Pike, the tool seems to work well. A minor issue, though: the display port (where I connect 27" Apple Cinema Display via DP>miniDP adapter) still is shown as port usused. As a matter of fact I have HDMI audio via HDMI port, but not from Display Port. Could it be related/solved by AppleIntelFramebufferAzul.sh?
The hardware: GA H81M-HD3, intel i3 4330
![schermata 2014-09-18 alle 12 06 23](https://cloud.githubusercontent.com/assets/6927676/4318165/8aa164a2-3f1b-11e4-9fec-06aa8ae5057f.png)

**Comment by Piker-Alpha** [comment]
You are the second person to mix port 3 with port 4 (everything after the / is for port 4) so I have changed a few things to hopefully solve this uses once and for all.

**Comment by giacomoleopardo** [comment]
Please note that I changed just the first two port's connector type from displayport to DVI (port 5) and from displayport to HDMI (port 6). No editing for the port 7 (always seen unused) or the VGA.

**Comment by Piker-Alpha** [comment]
Now I am confused. You wrote: "...is shown as port unused" and the only port that shows "unused" is the last one. What am I missing here?

**Comment by giacomoleopardo** [comment]
GA H81M-HD3 has four ports: DVI, HDMI, DP and VGA. Of course VGA is not supported, but why, DisplayPort is unused, when the only display I am using is Apple Cinema Display plugged into the display port?

**Comment by Piker-Alpha** [comment]
Right, You have four frame buffers (one for port 5, 6, 7 and the unused one for VGA) so I still don't get it. The script shows all data for all frame buffers (4 ports) and the only port in your screenshot with "unused" is the frame buffer for the VGA connector. Look here:

(port 7, DisplayPort connector / port unused …
VGA connector)

The text: "port 7, is DisplayPort connector" is for your DisplayPort connector" and the text: "/ port unused … VGA connector)" is the text for the frame buffer that would be used for the VGA connector (if it wasn't disabled by ff00).

Or do you see the text: "unused" somewhere else? In the port sub menu perhaps?

**Comment by giacomoleopardo** [comment]
Ok, now I get it.
Still, here what IORegistryExplorer shows about display port. No av-signal-type (00 00 00 00), nor port-number (0x0). How come? I guess it's a motherboard\port issue, not related to Azul editing.
BTW Mavericks 10.9.5.

![schermata 2014-09-19 alle 20 02 48](https://cloud.githubusercontent.com/assets/6927676/4339835/c6fb58d8-4027-11e4-9355-be3aa472e51e.png)

**Comment by Piker-Alpha** [comment]
I think that is due to the port attribute of the DisplayPort.Try 0000 0000 and change the pipe attribute to 0a00 (DVI 0900 and HDMI 0800 or vice versa).

**Comment by giacomoleopardo** [comment]
Do you mean like this?
If yes, no luck. Still port 0x0 (and no hdmi audio via dp port)
![schermata 2014-09-20 alle 00 04 25](https://cloud.githubusercontent.com/assets/6927676/4342736/f847872e-4048-11e4-8692-ab40c60e1d1f.png)
Even with pipe attribute DVI 0800 and HDMI 0900.

**Comment by Piker-Alpha** [comment]
Do the other two frame buffers list the correct connector types? If not, are you sure that the kernel cache is updated? Also. VGA is usually the first port on the motherboard, so you may want to try something like this:

00048718: 0000 0800 0100 0000 3000 0000 (port 0, VGA connector)
00048724: 0105 0900 0002 0000 8700 0000 (port 5, DVI connector)
00048730: 0204 0800 0008 0000 0600 0000 (port 6, HDMI connector)
0004873c: 0306 0a00 0004 0000 0000 0000 (port 7, DisplayPort connector)

About HDMI audio via DP. Was that working with this or some other connector attribute:
0004873c: 0306 0a00 0004 0000 1100 0000 (port 7, DisplayPort connector)

Note: The offsets are different. From 10.8.5 because I use a remote computer to test stuff on!

**Comment by giacomoleopardo** [comment]
Pike, I'm sorry for the time I took you. It tourned out that was a faulty version of Kext Wizard, my cache was not updated.
To summerize, the steps to make Azul working correctly on this board are:
- Change connector type for port 5 (from DisplayPort to DVI)
- change connector type for port 6 (from DisplayPort to HDMI)
- change connector attribute for port 7 (from 1100 0000 to 0000 0000)
- remove cache with terminal command sudo rm -r /System/Library/Caches/com.apple.kext.caches
- repair permission with terminal command sudo touch /System/Library/Extensions
- update kernel cache with terminal command sudo kextcache -update-volume /
  ![schermata 2014-09-20 alle 16 51 06](https://cloud.githubusercontent.com/assets/6927676/4345586/1adab32c-40d7-11e4-8b90-0d21c54503b4.png)

Now this is the result for Apple Cinama Display 27" via DisplayPort - miniDisplayPort adapter
![schermata 2014-09-20 alle 17 00 20](https://cloud.githubusercontent.com/assets/6927676/4345580/de6f55aa-40d6-11e4-8fc2-2b3bb447d25e.png)
![schermata 2014-09-20 alle 17 00 45](https://cloud.githubusercontent.com/assets/6927676/4345581/ef4aa1f4-40d6-11e4-9949-d442583f827c.png)

**Comment by Piker-Alpha** [comment]
No problem. I'm glad that everything is working now. Also. The script should take care of the kernel cache so I will check that for the next update. Thanks!
